### ISSUE TITLE
Plot gets cut at the end

### ISSUE THREAD

**Issue by curioustolearn** [racket/plot#82] opened 2021-01-06 15:54 UTC
The following is the code and picture of a plot. One can see that the axis labels at y = 4 and y = -1 get cut.

**Code**

```
#lang racket
(require plot/no-gui)


(plot-x-axis? #f)
(plot-y-axis? #f)
(plot-x-far-axis? #f)
(plot-y-far-axis? #f)

(define sqrplt (plot-file (list (y-axis 0 #:labels? #t)
                           (x-axis 0 #:labels? #t)
                           (function sqr -2 2)
                           (lines (list '(-2 1) '(1 2) '(3 1)))
                           (point-label '(0 1) "Plot" #:size 24 #:color "steelblue"))
                     "sqplot.svg"
                     ))
```

**Picture of the plot**

[sqplot.pdf](https://github.com/racket/plot/files/5776738/sqplot.pdf)

Thank you.

**Comment by alex-hhh** [comment] 2021-01-07 00:32
This is expected behavior, but I agree that it is somewhat surprising.  To better understand what is happening, I changed the plot to draw the axes around the plot and also changed the plot background to blue and the plot area to yellow:

```racket
#lang racket
(require plot)

(plot-background "lightblue")

(plot (list
       (rectangles (list (vector (ivl -inf.0 +inf.0) (ivl -inf.0 +inf.0)))
                   #:color "lightyellow"
                   #:line-style 'transparent)
       (y-axis 0 #:labels? #t)
       (x-axis 0 #:labels? #t)
       (function sqr -2 2)
       (lines (list '(-2 1) '(1 2) '(3 1)))
       (point-label '(0 1) "Plot" #:size 24 #:color "steelblue")))
```

This produces:

![colored-bg](https://user-images.githubusercontent.com/11592690/103834709-24203c00-50bf-11eb-92a2-9f060c968a20.png)

In the above image, the yellow area is the **plot area** and everything that you plot (i.e. the actual arguments to the plot function, like `x-axis`, `y-axis`, `function`, `lines`, etc) will be clipped to this area. -- this includes any text labels, where part of the text might be cut off.   The blue area is the size of the plot, and the plot package will calculate this so that all plot decorations (axis labels, tick labels and title) actually fit in the plot -- note however that the `x-axis` is not a plot decoration but a plot renderer and it is drawn inside the plot area, so it is clipped to it.

The plot package determines the size of this area to fit all the elements it can find, in your case, it makes it so that the square function from -2 to 2 will fit (making the y axis go from 0 to 4), and the other elements, like the lines and the point label also fit in this area.  The text for the labels is not considered when calculating the size of the area.

You have two options:

The first option is to slightly extend the size of the plot area, so that the tick labels fit.  This can be done using the `#:x-min`, `#:x-max`, `#:y-min`, `#:y- max` arguments to the `plot` call.  For example you can extent the maximum y value to 4.1:

```racket
#lang racket
(require plot)

(plot-background "lightblue")

(plot (list
       (rectangles (list (vector (ivl -inf.0 +inf.0) (ivl -inf.0 +inf.0)))
                   #:color "lightyellow"
                   #:line-style 'transparent)
       (y-axis 0 #:labels? #t)
       (x-axis 0 #:labels? #t)
       (function sqr -2 2)
       (lines (list '(-2 1) '(1 2) '(3 1)))
       (point-label '(0 1) "Plot" #:size 24 #:color "steelblue"))
      #:y-max 4.1)
```

![colored-bg-1](https://user-images.githubusercontent.com/11592690/103835334-f2a87000-50c0-11eb-8893-b11eb9c585c8.png)

The second option is to write your own tick function to not plot a label if it is close to the limit of the plot.  This is more complex, but gives you more flexibility:

```racket
#lang racket
(require plot plot/utils)

(plot-background "lightblue")

(define my-ticks
  (ticks (linear-ticks-layout)
         (lambda (low high pre-ticks)
           (define digits (digits-for-range low high))
           (define range (- high low))
           (define cutoff 0.05)
           (define low-cutoff (+ low (* cutoff range)))
           (define high-cutoff (- high (* cutoff range)))
           (for/list ([t (in-list pre-ticks)])
             (let ((value (pre-tick-value t)))
               (if (and (pre-tick-major? t) (> value low-cutoff) (< value high-cutoff))
                   (~r value #:precision digits)
                   ""))))))

(parameterize ([plot-x-ticks my-ticks]
               [plot-y-ticks my-ticks])
  (plot (list
         (rectangles (list (vector (ivl -inf.0 +inf.0) (ivl -inf.0 +inf.0)))
                     #:color "lightyellow"
                     #:line-style 'transparent)
         (y-axis 0 #:labels? #t)
         (x-axis 0 #:labels? #t)
         (function sqr -2 2)
         (lines (list '(-2 1) '(1 2) '(3 1)))
         (point-label '(0 1) "Plot" #:size 24 #:color "steelblue"))))
```

![plot-3](https://user-images.githubusercontent.com/11592690/103836027-cbeb3900-50c2-11eb-962e-e1345b61d4b5.png)

**Comment by curioustolearn** [comment] 2021-01-07 17:50
Thank you very much for the clear explanation. For now I will extend the plot area a little so that the tick labels fit. The other solution looks complicated to me. Is there also a way to place only specified ticks (for example, as a list)? Matplotlib in python, for example allows specifying the value and the tick labels for those values. Example from their documentation:

```
 xticks((0,1,2,3,4), ('Tom', 'Dick', 'Harry', 'Sally', 'Sue'))
```

Is it possible to do something like that?

Thank you.

**Comment by alex-hhh** [comment] 2021-01-08 01:28
There is no direct support for specifying the values and labels directly, but you can easily write your own.  You will need to define a `ticks` structure containing a layout function and a labeling function:

* The layout function takes an interval, `low`, `high` and produces `pre-tick` values for each tick on the axis.  `make-fixed-ticks-layout` constructs such a function by providing pre-ticks from the list of supplied `positions`
* the labeling function takes a list of pre-ticks and returns the labels. `make-fixed-ticks-labels` constructs such a function by looking up the label for a specified position
* finally, `fixed-ticks` produces the required ticks structure by combining these two functions together

You can check the plot documentation for `ticks`, `ticks-layout/c` and `ticks-format/c` for more information.

```racket
(define (make-fixed-ticks-layout positions)
  (lambda (low high)
    (for/list ([p (in-list positions)]
               #:when (and (>= p low) (<= p high)))
      (pre-tick p #t))))

(define (make-fixed-ticks-labels positions labels)
  (lambda (low high pre-ticks)
    (for/list ([t (in-list pre-ticks)])
      (let ([value (pre-tick-value t)])
        (if (pre-tick-major? t)
            (or (for/first ([p (in-list positions)]
                            [l (in-list labels)]
                            #:when (equal? p value))
                  l)
                "")
            "")))))

(define (fixed-ticks positions labels)
  (ticks (make-fixed-ticks-layout positions)
         (make-fixed-ticks-labels positions labels)))
```

And here is how you can use them:

```racket
(parameterize ([plot-y-ticks (fixed-ticks '(0 1 2 3 4)
                                          '("Tom" "Dick" "Harry" "Sally" "Sue"))])
  (plot (list
         (rectangles (list (vector (ivl -inf.0 +inf.0) (ivl -inf.0 +inf.0)))
                     #:color "lightyellow"
                     #:line-style 'transparent)
         (y-axis 0 #:labels? #t)
         (x-axis 0 #:labels? #t)
         (function sqr -2 2)
         (lines (list '(-2 1) '(1 2) '(3 1)))
         (point-label '(0 1) "Plot" #:size 24 #:color "steelblue"))
        #:y-min -1 #:y-max 5))
```

![plot](https://user-images.githubusercontent.com/11592690/103962847-d248e600-5192-11eb-9e63-b0d5a84bf434.png)

**So why is this so complicated?** The plot package allows zooming in plots and in such cases, plot ticks are re-calculated to make the plot more useful -- for example, if you zoom in on the previous plot, the labels will disappear of you zoom in the plot to an interval between 0.5 and 0.6, for example, since the ticks are fixed at 0, 1, 2, 3, etc.  So, while reusable, the `fixed-ticks` function has limited general use.

----

On a separate note, can you please direct further questions about the plot package and racket in general to the racket-users group or the slack channel, so other user also benefit from the discussion. The plot issue tracker is for bug reports and enhancement requests.  I will close this issue as it is not a bug and I believe I have addressed your questions. Thanks.

**Closed by alex-hhh** 2021-01-08 01:28 UTC
