### ISSUE TITLE
plot-frame's frame is too small

### ISSUE THREAD

**Issue by LiberalArtist** [racket/plot#39] opened 2018-02-22 17:47 UTC
I recently tried using `plot-frame` for the first time, and (at least on Mac OS) the resulting frame cuts off the plot half-way through the x-axis labels. Resizing the window causes the plot to be resized to fit correctly within the frame. 

Here are a minimal example and a screenshot:
```racket
#lang racket

(require plot)

(send (plot-frame (points '((2010 39.4)
                            (2010 93.8)
                            (2011 40.3)
                            (2011 79.9)
                            (2012 44.0)
                            (2012 85.5)))
                  #:x-label "Year"
                  #:y-label "Temperature [F]")
      show
      #t)
```
<img width="420" alt="plot-frame" src="https://user-images.githubusercontent.com/10700996/36554829-ea04b4ea-17c5-11e8-8498-dc9715cfc8d2.png">

**Comment by alex-hhh** [comment] 2018-02-24 00:05
Actually, the snip is too big :-) I proposed a fix for this.  The problem is present in Racket 6.11 as well...

**Comment by bennn** [comment] 2018-03-28 04:00
https://github.com/racket/plot/commit/b1a27914d88af828fb68105820808714e9a41127

**Closed by bennn** 2018-03-28 04:00 UTC
