### ISSUE TITLE
Segfault in plot tests

### ISSUE THREAD

**Issue by takikawa** [racket/plot#2] opened 2015-03-04 21:12 UTC
I tried to run the `plot/tests/typed/parameter-regression-tests.rkt` in DrRacket and get a segfault. It appears that just opening this file (also `plot-pict.rkt` in the same directory) and waiting for background compilation to finish will trigger a segfault.

@stamourv was also able to reproduce this on his machine.

**Comment by ntoronto** [comment] 2015-03-05 16:22
I can't reproduce this on 6.1.1.8--2015-01-31. I'll try updating and see what I get.

The fact that background compilation can set it off suggests a Typed Racket error, but I'll try to reproduce it before punting.

**Comment by mflatt** [comment] 2015-03-05 16:31
I can replicate it. I think the problem is in the macro expander.

**Comment by ntoronto** [comment] 2015-03-05 16:56
I can't replicate the crash, but I'm not getting any plot snips at all. For example, this program gives me two plots, a file, and a useless single-pixel I-don't-know-what-it-is:
```racket
#lang racket
(require plot)
(plot-pict (function sin -3 3))
(plot-bitmap (function sin -3 3))
(plot-file (function sin -3 3) "blah.png")
(plot-snip (function sin -3 3))
```

I'd suggest looking in "plot/plot-gui-lib/plot/private/gui/untyped.rkt", which defines untyped wrappers for lazily-required untyped code that creates snips, and "plot/plot-gui-lib/plot/private/gui/plot2.rkt", which imports those wrappers using `require/typed`.

**Comment by mflatt** [comment] 2015-03-05 19:46
I've pushed a repair for the crash

**Comment by ntoronto** [comment] 2015-03-10 00:01
I'll close this, then. The single-pixel-snip problem appears to be unrelated, and I've submitted a bug report for it.

**Closed by ntoronto** 2015-03-10 00:01 UTC
